# @package _global_
defaults:
  - /unf
  - override /net: lgatr
  - override /dataset: yukawa
  - _self_

norm: l1

data:
  on_gpu: true
  
dataset:
  reader:
    path: '/remote/gpu07/huetsch/memennto/data'
    num: null
  process:
    _target_: src.datasets.YukawaEquiProcess

net:
  backbone:
    in_v_channels: 1
    in_s_channels: 3 # one hot pid
    hidden_v_channels: 8
    hidden_s_channels: 32
    num_blocks: 4
    num_heads: 4
    compile: True
  
training:
  lr: 0.001
  batch_size: 2048
  optimizer:
    warmup_steps: 5000
    weight_decay: 0.0
