# @package _global_
defaults:
  - /unf
  - override /dataset: zjet_corrected
  - _self_

net:
  dim_in: ${dataset.process.num_features}
  dim_out: 1
  ensembled: 20

training:
  lr: 1e-4
  optimizer:
    warmup_steps: 5000
    betas: [0.90,0.999]