# @package _global_
defaults:
  - /unf
  - override /dataset: zjet
  - _self_

net:
  dim_in: ${dataset.process.num_features}
  dim_out: 1
  ensembled: false

training:
  lr: 5e-3
  optimizer:
    warmup_steps: 5000