
_target_: src.networks.LGATr
backbone:
  _target_: lgatr.LGATrSlim
  in_v_channels: 1
  out_v_channels: 0
  hidden_v_channels: 8
  in_s_channels: 1
  out_s_channels: ${net.backbone.hidden_s_channels}
  hidden_s_channels: 16
  num_blocks: 2
  num_heads: 1
  nonlinearity: gelu
  mlp_ratio: 2
  attn_ratio: 1
  num_layers_mlp: 2
  dropout_prob: null
  checkpoint_blocks: false
  compile: false
head:
  _target_: src.networks.MLP
  dim_in: ${net.backbone.out_s_channels}
  dim_out: 1
  hidden_channels: ${net.backbone.out_s_channels}
  num_hidden_layers: 1
  act: silu
  out_act: null
  drop: 0
  bayesian: false
  bayesian_prior_prec: 1.0
  ensembled: null
  layernorms: false