_target_: src.networks.MLP
dim_in: ???
dim_out: ???
hidden_channels: 96
num_hidden_layers: 4
act: silu
out_act: null
drop: null
bayesian: false
bayesian_prior_prec: 1.0
# init_gain: 1.0 # only used if ensembling
# out_bias_gain: 1.0 # only used if ensembling
ensembled: null
layernorms: false