defaults:
  - /default
  - /net: mlp
  - _self_

run_name: classify_${dataset.name}
experiment: ClassificationExperiment

prev_it_path: null

loss: bce
bayesian: false

model:
  _target_: src.models.Classifier

# net:
#   dim_in: ${dataset.dim}
#   dim_out: 1
#   bayesian: ${bayesian}

training:
  lr: 1e-3
  epochs: 500
  batch_size: 1024
  patience: 50
  optimizer:
    weight_decay: 0.01
    # warmup_steps: 5000

data:
  on_gpu: true