defaults:
  - /default
  - /net: mlp
  - _self_

run_name: classify_${dataset.name}
experiment: ClassificationExperiment

prev_it_path: null

loss: bce

model:
  _target_: src.models.Classifier


training:
  lr: 1e-3
  epochs: 500
  batch_size: 1024
  patience: 50
  optimizer:
    weight_decay: 0.0

data:
  on_gpu: true