defaults:
  - /cls
  - override net: transformer2
  - override dataset: omnifold_particle
  - _self_

data:
  on_gpu: false

dataset:
  reader:
    use_cond: True
  process:
    _target_: src.datasets.OmniFoldParticleCondProcess

net:
  dim_cond: 4

training:
  batch_size: 256
  test_batch_size: 256
  optimizer:
    warmup_steps: 5000
    weight_decay: 0.03
