defaults:
  - /cls
  - override dataset: gaussian_toy
  - _self_

net:
  num_hidden_layers: 2
  hidden_channels: 32
  ensembled: 64

training:
  epochs: 1
  batch_size: 512
  test_batch_size: 8192
  optimizer:
    warmup_steps: 5000
    weight_decay: 0.0