defaults:
  - /default
  - /net: mlp
  - _self_

run_name: unfold_${dataset.name}
experiment: UnfoldingExperiment

cls_path: ???

loss: mlc
norm: l1
bayesian: false

model:
  _target_: src.models.Unfolder

net:
  dim_in: ${dataset.dim}
  dim_out: 1
  bayesian: ${bayesian}

training:
  lr: 1e-3
  epochs: 500
  batch_size: 4096
  patience: 50

data:
  on_gpu: true
