defaults:
  - /default
  - /net: mlp
  - _self_

run_name: unfold_${dataset.name}
experiment: UnfoldingExperiment

cls_path: ???
prev_it_path: null

loss: mlc
norm: l1
joint_ensembling: false
norm_target: false

model:
  _target_: src.models.Unfolder

training:
  lr: 1e-3
  epochs: 500
  batch_size: 4096
  test_batch_size: ${training.batch_size}
  patience: 50
  optimizer:
    betas: [0.98, 0.999]

data:
  on_gpu: true
