defaults:
  - /unf
  - override dataset: gaussian_toy
  - _self_

norm: l1

net:
  num_hidden_layers: 2
  hidden_channels: 32
  ensembled: 64

training:
  lr: 1e-05
  epochs: 1
  batch_size: 512
  optimizer:
    warmup_steps: 5000
    weight_decay: 0.0

