name: omnifold_cartesian
reader:
  _target_: src.datasets.OmniFoldCartesianData.read
  path: /remote/gpu02/ore/data/energyflow
  observables_path: /remote/gpu02/ore/station/data
process:
  _target_: src.datasets.OmniFoldCartesianProcess  