name: ttbar
reader:
  _target_: src.datasets.ttbarData.read
  path: /remote/gpu02/ore/theofold/data
  ms_dat: [1725]
  ms_sim: [1695,1755]
process:
  _target_: src.datasets.ttbarProcess
  num_features: 16  

