name: zjet_particle
reader:
  _target_: src.datasets.ZJetParticleData.read
  path: /remote/gpu02/ore/data/energyflow
  observables_path: /remote/gpu02/ore/station/data
process:
  _target_: src.datasets.ZJetParticleProcess  
  num_features: 4