# @package _global_
defaults:
  - /itr
  - /cls@cls: yukawa_equi
  - /unf@unf: yukawa_equi
  - override /dataset: yukawa
  - _self_

dataset:
    process:
      _target_: src.datasets.YukawaEquiProcess