# @package _global_
defaults:
  - /cls
  - override /dataset: gaussian
  - _self_

net:
  dim_in: ${dataset.process.num_features}
  dim_out: 1
  num_hidden_layers: 2
  hidden_channels: 32
  ensembled: 64

training:
  lr: 5e-03
  epochs: 1
  batch_size: 8192
  test_batch_size: 8192
  optimizer:
    warmup_steps: 200
    weight_decay: 0.0